-- Run as SECURITYADMIN (for role/user grants)
USE ROLE SECURITYADMIN;

-- Create roles
CREATE ROLE IF NOT EXISTS ENERGY_PLATFORM_ADMIN;
CREATE ROLE IF NOT EXISTS ENERGY_ANALYST_RO;
CREATE ROLE IF NOT EXISTS ENERGY_APP_RO;

-- Attach to parent roles (so SYSADMIN can manage)
GRANT ROLE ENERGY_PLATFORM_ADMIN TO ROLE SYSADMIN;

-- Attach read-only roles to appropriate parents (choose what fits your org)
GRANT ROLE ENERGY_ANALYST_RO TO ROLE SYSADMIN;
GRANT ROLE ENERGY_APP_RO     TO ROLE SYSADMIN;
