USE ROLE SYSADMIN;

-- Ingest / ELT warehouse (used by admin + Databricks-triggered jobs)
CREATE WAREHOUSE IF NOT EXISTS WH_INGEST
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 10
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- BI / dashboard warehouse
CREATE WAREHOUSE IF NOT EXISTS WH_BI
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 15
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

-- Grants
GRANT USAGE ON WAREHOUSE WH_INGEST TO ROLE ENERGY_PLATFORM_ADMIN;

GRANT USAGE ON WAREHOUSE WH_BI
  TO ROLE ENERGY_ANALYST_RO;
GRANT USAGE ON WAREHOUSE WH_BI
  TO ROLE ENERGY_APP_RO;
