USE ROLE SYSADMIN;
USE DATABASE energy_data;
USE SCHEMA gold;

-- Database & schema usage
GRANT USAGE ON DATABASE energy_data TO ROLE ENERGY_PLATFORM_ADMIN;
GRANT USAGE ON DATABASE energy_data TO ROLE ENERGY_ANALYST_RO;
GRANT USAGE ON DATABASE energy_data TO ROLE ENERGY_APP_RO;

GRANT USAGE ON SCHEMA energy_data.gold TO ROLE ENERGY_PLATFORM_ADMIN;
GRANT USAGE ON SCHEMA energy_data.gold TO ROLE ENERGY_ANALYST_RO;
GRANT USAGE ON SCHEMA energy_data.gold TO ROLE ENERGY_APP_RO;

-- Table privileges (Gold only)
GRANT SELECT, INSERT, UPDATE, DELETE
  ON ALL TABLES IN SCHEMA energy_data.gold
  TO ROLE ENERGY_PLATFORM_ADMIN;
GRANT SELECT
  ON ALL TABLES IN SCHEMA energy_data.gold
  TO ROLE ENERGY_ANALYST_RO;
GRANT SELECT
  ON ALL TABLES IN SCHEMA energy_data.gold
  TO ROLE ENERGY_APP_RO;

-- Ensure future tables are covered
GRANT SELECT, INSERT, UPDATE, DELETE
  ON FUTURE TABLES IN SCHEMA energy_data.gold
  TO ROLE ENERGY_PLATFORM_ADMIN;
GRANT SELECT
  ON FUTURE TABLES IN SCHEMA energy_data.gold
  TO ROLE ENERGY_ANALYST_RO;
GRANT SELECT
  ON FUTURE TABLES IN SCHEMA energy_data.gold
  TO ROLE ENERGY_APP_RO;

-- Stage usage: admin role needs to read from S3 stage
GRANT USAGE ON STAGE s3_export_stage TO ROLE ENERGY_PLATFORM_ADMIN;
