SELECT CURRENT_ROLE(), CURRENT_USER();

CREATE WAREHOUSE IF NOT EXISTS tiny_wh
  WAREHOUSE_SIZE = XSMALL
  AUTO_SUSPEND = 15
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE;

CREATE OR REPLACE STORAGE INTEGRATION s3_export_int
  TYPE = EXTERNAL_STAGE
  STORAGE_PROVIDER = S3
  ENABLED = TRUE
  STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::155754084742:role/DatabricksS3AccessRole'
  STORAGE_ALLOWED_LOCATIONS = ('s3://energy-data-platform-project/export/');

DESCRIBE STORAGE INTEGRATION s3_export_int;